# Generated by Django 3.2 on 2022-07-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0007_auto_20220714_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='related',
            new_name='name',
        ),
    ]
