# Generated by Django 3.2 on 2022-07-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislations', '0002_legislationlistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislationpage',
            name='date_into_practice',
            field=models.DateField(blank=True, null=True),
        ),
    ]
